greenGrass_shop/cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<product_id>/', views.cart_add, name='cart_add'),
    path('remove/<product_id>/', views.cart_remove, name='cart_remove'),
]

greenGrass_shop/greenGrass_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include(('cart.urls', 'cart'), namespace='cart')),
    path('', include(('orders.urls', 'orders'), namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greenGrass_shop/orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

greenGrass_shop/shop/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('category/<category_slug>/',  views.main_catalog, name='product_list_by_category'),
    path('id=<id>/<slug>', views.product_detail, name='product_detail'),
    path('catalog/', views.main_catalog, name='main_catalog'),
]

greenGrass_shop/orders/models.py
from django.db import models
from shop.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Фамилия')
    last_name = models.CharField(max_length=50, verbose_name='Имя')
    email = models.EmailField(verbose_name='Эл.почта')
    address = models.CharField(max_length=250, verbose_name='Адрес')
    city = models.CharField(max_length=100, verbose_name='Город')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=20, default=+7, verbose_name='Телефон')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

greenGrass_shop/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_length=0, decimal_places=2, max_digits=10)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

greenGrass_shop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

greenGrass_shop/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'address', 'city']

greenGrass_shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .forms import CartAddProductForm
from .cart import Cart
from shop.models import Product


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_detail.html', {'cart': cart})

greenGrass_shop/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form})

greenGrass_shop/shop/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def main_page(request):
    return render(request,
                  'shop/index.html',
                  )

def main_catalog(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug is not None:
        category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category__slug=category_slug)
    context = {
        'category': category,
        'categories': categories,
        'products': products
    }
    return render(request,
                  'shop/catalog.html',
                  context)


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product_info': product,
                                                        'cart_product_form': cart_product_form})

greenGrass_shop/cart/templates/cart/cart_detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
<div class="container-xxl cart_detail">
    <div class="text-center">
    <h1>Список товаров в корзине:</h1>
        <div class="container-fluid">
        {% for item in cart %}
            {% with product=item.product %}
            <div class="container-fluid d-flex justify-content-around align-items-center text-left">
                <div class="col">
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                        </a>
                </div>
                <div class="col">
                    <p>{{ product.name }}</p>
                </div>
                <div class="col">
                    <p>{{ item.quantity }}</p>
                </div>
                <div class="col">
                    <p><a href="{% url "cart:cart_remove" product.id%}">Удалить</a></p>
                </div>
                <div class="col">
                    <p class="num">{{ item.price }} руб.</p>
                </div>
                <div class="col">
                    <p class="num">{{ item.total_price }} руб.</p>
                </div>
                </div>
            {% endwith %}
        {% endfor %}
        <div class="container-fluid">
        <div class="total">
            <h5>Итого:</h5>
            <h5 class="num">{{ cart.get_total_price }} руб.</h5>
        </div>
        
        <p class="text-right">
            <a href="{% url "shop:main_catalog" %}" class="button light">Вернуться в каталог</a>
            <a href="{% url "orders:order_create" %}" class="button">
                Заказать
            </a>
        </p>
        </div>
        </div>
</div>
</div>
{% endblock %}

greenGrass_shop/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}Checkout{% endblock %}

{% block content %}
<div class="container-xxl text-center">

    <h1>Оформить заказ</h1>
    <div class="order-info">
        <h3>Ваш заказ:</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Итого: {{ cart.get_total_price }} руб.</p>
    </div>

    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Заказать"></p>
        {% csrf_token %}
    </form>

</div>
{% endblock %}

greenGrass_shop/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
<div class="conteriner-xxl created text-center">
    <h1>Спасибо за заказ!</h1>
    <p>Заказ сформирован, скоро мы свяжемся с Вами. Номер заказа:
        <strong>{{ order.id }}</strong>.</p>
</div>
{% endblock %}

greenGrass_shop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}GGshop | GreenGrass.ru{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>GGshop | GreenGrass.ru</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Alegreya+Sans:ital,wght@0,100;0,300;0,400;0,500;0,700;0,800;0,900;1,100;1,300;1,400;1,500;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />
</head>
<body>
<div class="container-fluid">
      <div class="row justify-content-center">
        <div class="head d-inline-flex text-center align-items-center">
          <div class="col-4">
            <button href="tel:+74959999932" class="head_placeholder_phone">
              <img
                class="head_phone_icon"
                src="{% static "/img/phone_icon.png" %}"
                alt="phone"
              />
              <p class="phone d-inline-block">+7(495)999-99-32</p>
            </button>
          </div>
          <div class="col-4">
            <div class="head_menu">
              <ul class="head_ul_menu justify-content-center">
                <li class="head_li_menu">
                  <a class="head_li_menu_link" href="{% url 'shop:main_page' %}">Главная</a>
                </li>
                <li class="head_li_menu">
                  <a class="head_li_menu_link" href="{% url 'shop:main_catalog' %}">Каталог</a>
                </li>
                <li class="head_li_menu">
                  <a class="head_li_menu_link" href="#">Информация</a>
                </li>
                <li class="head_li_menu">
                  <a class="head_li_menu_link" href="#">Контакты</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-4">
            <div class="head_buttons">
              <form action="{% url 'cart:cart_detail' %}">
                <button class="head_button">
                  <div class="cart">
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            Корзина: 
                                {{ cart.get_total_price }} руб.
                        {% else %}
                            Корзина пуста.
                        {% endif %}
                    {% endwith %}
                  </div>
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

greenGrass_shop/shop/templates/shop/catalog.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Каталог{% endif %}
{% endblock %}
{% block content %}

<div class="container-xxl body_catalog">
      <div class="row">
        <div class="category_bar text-center    ">
          <ul class="category_menu_item d-flex justify-content-around">
            <li  {% if not category %}class="selected"{% endif %}>
                <a class="category_menu_item_link" href="{% url "shop:main_catalog" %}">Все товары</a>
            </li>
                {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                        <a class="category_menu_item_link" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
      </div>
</div>


<div id="main" class="container-xxl catalog_list">
    <div class="row text-center align-items-center">
            <div id="main" class="container-xxl">
                <h1 class="category_title">{% if category is not None %}
                     {{ category.name }}
                     {% else %}Все товары{% endif %}</h1>
                    {% for product in products %}
                    <div class="container-fluid d-flex justify-content-between align-items-center product_cart">
                        <div class="col"><a href="{{ product.get_absolute_url }}">
                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                        </a></div>
                        <div class="col">
                        <a class="product_name" href="{{ product.get_absolute_url }}">{{ product.name }}</a></div>
                        <div class="col"><form class="price_button">{{ product.price }} руб. 00 коп.</form></div>
                    </div>
                    {% endfor %}
            </div>
    </div>
</div>

{% endblock %}

greenGrass_shop/shop/templates/shop/index.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Каталог{% endif %}
{% endblock %}
{% block content %}

<div id="subheader">
    <div class="container-xxl body_home">
      <div class="row justify-content-center align-items-center">
        <div class="col-10">
          <div class="home_main_div">
            <div class="home_title">
              <h1>Выращиваем микрозелень под заказ</h1>
              <img src="" alt="" />
            </div>
            <div class="home_subtitle">
              <h2>
                Достаточно оформить заказ, доставка по Москве в течение 7 дней
              </h2>
            </div>
          </div>
        </div>
        <div class="col-2">
          <div class="home_truc_icon">
            <img src="{% static "/img/truck-tick.svg" alt="truck_icon" %}"/>
          </div>
        </div>
        <div class="home_btn">
          <a class="home_main_button" href="{% url 'shop:main_catalog' %}">
            <button class="home_main_button">
            Каталог <img src="{% static "/img/catalog.svg" alt="calatog" %}"/>
            </button>
          </a>
        </div>
      </div>
    </div>

{% endblock %}

greenGrass_shop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %} 
{% load static %} 
{% block title %} 
{% if product_info %} {{ product_info.name }} {% else %} Products {% endif %}
{% endblock %} 

{% block content %}
    <div class="container-xxl product_detail_cart">


      <div class="product_detail_cart d-block p-2">
        <div class="text-center">
          <img class="product_detail_cart_image" src="{% if product_info.image %}{{ product_info.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" alt="">
        </div>
        <h1 class="product_detail_cart_name">{{ product_info.name }}</h1>
        <p class="product_detail_cart_description">{{ product_info.description }}</p>
      </div>


      <div class="container-fluid d-flex justify-content-between  text-center">
        <div class="col">
          <p class="product_detail_cart_stock"><button class="price_button">Осталось в наличии: {{ product_info.stock }}</button></p>
        </div>
        <div class="col">
          <p class="product_detail_cart_price"><button class="price_button">Цена: {{ product_info.price }}</button></p>
        </div>

        <div class="col">

            <form  action="{% url "cart:cart_add" product_info.id %}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input class="add_product_button" type="submit" value="Добавить">
            </form>

        </div>
      </div>


    </div>

{% endblock %}

greenGrass_shop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

greenGrass_shop/shop/templates/shop/product/not_use_list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}